version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      LEVEL_NAME: amy-archipelago
    ports:
      - 19132:19132/udp
    volumes:
      - ./worlds:/data/worlds
    stdin_open: true
    tty: true

